server:
  port : 8081

spring:
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
    pool:
      initial-size: 2
      max-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false