POST http://localhost:8081/api/v1
Content-Type: application/json

{
  "id": 6,
  "userId": 3,
  "count": 123464,
  "balance": 5000,
  "type": "INVOICE"
}


###
GET http://localhost:8081/api/v1/product/3

###
GET http://localhost:8081/api/v1/checkProduct?type=CARD
USERID: 12345655555

###
GET http://localhost:8081/api/v1/getAllProductByUserId?userId=0

###
GET http://localhost:8081/api/v1/getAllProductByUserId

###
POST http://localhost:8082/api/v1/product
Content-Type: application/json

{
  "id": 4,
  "code": "EXAMPLE"
}

###
GET http://localhost:8082/api/v1/product/checkProduct?type=CARD
USERID: 2
###
