POST http://localhost:8080/api/v1/createProduct
Content-Type: application/json

{
  "id": 4,
  "userId": 3,
  "count": 654654,
  "balance": 600000,
  "type": "INVOICE"
}


###
GET http://localhost:8080/api/v1/getProductById?id=3

###
GET http://localhost:8080/api/v1/getAllProductByUserId?userId=3


