POST http://localhost:8081/api/v1/product
Content-Type: application/json

{
  "id": 6,
  "userId": 3,
  "count": 123464,
  "balance": 5000,
  "type": "INVOICE"
}


###
GET http://localhost:8081/api/v1/product/3
USERID: 2

###
GET http://localhost:8081/api/v1/products

###
GET http://localhost:8081/api/v1/products?userId=2

###
POST http://localhost:8082/api/v1/product
Content-Type: application/json

{
  "id": 4,
  "code": "EXAMPLE"
}

###
GET http://localhost:8082/api/v1/product/check?type=CARD
USERID: 2
###
GET http://localhost:8081/api/v1/check?type=CARD
USERID: 1234555
